
export const LOCAL_STORAGE_KEYS = {
  RECEIPTS: 'expenseAppReceipts',
  EXPENSE_ITEMS: 'expenseAppItems',
  TRIPS: 'expenseAppTrips',
};

export const CATEGORIES = [
  '6120 Fringe Staff Education',
  '7336 OVERHEAD COSTS:OH Seminars/Trainings',
  '7580 OH Travel',
  '7585 OH Business Meals',
  '8190 G&A Office supplies',
  '8197 G&A Office parking/tolls',
  '8207 G&A Conference/Seminar',
  '8231 BD Travel',
  '8232 BD Meals',
  '8321 G&A Business meals',
  '8330 G&A Office supplies',
  '9080 Employee Morale',
  '5400 Direct Travel',
  '5450 Direct Lodging',
  '5500 Direct Meals and Incidental',
  '8320 G&A Travel',
];

export const PROJECTS = [
  'Air Force AFWERX D2P2',
  'Air Force FORECAST',
  'SRS HATC (Humanitarian Aid Tech. Concept)',
  'BD',
  'BD Cyber Range',
  'Boeing A&P COI',
  'CACI AMOD',
  'CACI FICA',
  'CACI Hyperion',
  'CCRi CATO',
  'CCRi Megalodon',
  'Copper River Blue Steel',
  'EAS Predictive Analytics',
  'CMG C5',
  'G&A',
  'G&A B&P',
  'G&A B&P TerraChat',
  'G&A BD',
  'G&A CMMC',
  'G&A G&A',
  'G&A IR&D (BCKG)',
  'G&A IR&D (CAST IRON)',
  'G&A IR&D (Cyber Range/RoboCOP)',
  'G&A IR&D (Rubicon)',
  'G&A IR&D (SOCOM CRADA)',
  'G&A IR&D (STARbase)',
  'G&A Marketing',
  'IEX SOCOM GAP',
  'Ironclad MEAD',
  'IT Concepts IMD-T',
  'IT Concepts OHR Workforce Analytics (TO3)',
  'Overhead',
  'Peraton TALOS',
  'Pi Health FICS Ph III',
  'SOCOM CRADA',
  'SOCOM Rubicon TO 03',
  'SOCOM Rubicon TO 04',
  'SOFWERX Rapid AI',
  'SOFWERX SAIDAR',
  'STResearch DEMOS GeoFly',
  'STResearch Grasshopper SIREN',
  'STResearch Groot',
  'STResearch SABI Ph4',
  'VivSoft',
  'AAPE',
  'NICE Phase II',
  'G&A IR&D (Proposal Tech)',
  'DGS Next Gen',
  'STResearch Digiheals',
  'Army: CDAO-APT, EA, and AWG',
  'STResearch SABI Ph5 ECO',
];

export const US_STATES = [
    { name: 'Alabama', abbr: 'AL' }, { name: 'Alaska', abbr: 'AK' }, { name: 'Arizona', abbr: 'AZ' },
    { name: 'Arkansas', abbr: 'AR' }, { name: 'California', abbr: 'CA' }, { name: 'Colorado', abbr: 'CO' },
    { name: 'Connecticut', abbr: 'CT' }, { name: 'Delaware', abbr: 'DE' }, { name: 'Florida', abbr: 'FL' },
    { name: 'Georgia', abbr: 'GA' }, { name: 'Hawaii', abbr: 'HI' }, { name: 'Idaho', abbr: 'ID' },
    { name: 'Illinois', abbr: 'IL' }, { name: 'Indiana', abbr: 'IN' }, { name: 'Iowa', abbr: 'IA' },
    { name: 'Kansas', abbr: 'KS' }, { name: 'Kentucky', abbr: 'KY' }, { name: 'Louisiana', abbr: 'LA' },
    { name: 'Maine', abbr: 'ME' }, { name: 'Maryland', abbr: 'MD' }, { name: 'Massachusetts', abbr: 'MA' },
    { name: 'Michigan', abbr: 'MI' }, { name: 'Minnesota', abbr: 'MN' }, { name: 'Mississippi', abbr: 'MS' },
    { name: 'Missouri', abbr: 'MO' }, { name: 'Montana', abbr: 'MT' }, { name: 'Nebraska', abbr: 'NE' },
    { name: 'Nevada', abbr: 'NV' }, { name: 'New Hampshire', abbr: 'NH' }, { name: 'New Jersey', abbr: 'NJ' },
    { name: 'New Mexico', abbr: 'NM' }, { name: 'New York', abbr: 'NY' }, { name: 'North Carolina', abbr: 'NC' },
    { name: 'North Dakota', abbr: 'ND' }, { name: 'Ohio', abbr: 'OH' }, { name: 'Oklahoma', abbr: 'OK' },
    { name: 'Oregon', abbr: 'OR' }, { name: 'Pennsylvania', abbr: 'PA' }, { name: 'Rhode Island', abbr: 'RI' },
    { name: 'South Carolina', abbr: 'SC' }, { name: 'South Dakota', abbr: 'SD' }, { name: 'Tennessee', abbr: 'TN' },
    { name: 'Texas', abbr: 'TX' }, { name: 'Utah', abbr: 'UT' }, { name: 'Vermont', abbr: 'VT' },
    { name: 'Virginia', abbr: 'VA' }, { name: 'Washington', abbr: 'WA' }, { name: 'West Virginia', abbr: 'WV' },
    { name: 'Wisconsin', abbr: 'WI' }, { name: 'Wyoming', abbr: 'WY' }, { name: 'District of Columbia', abbr: 'DC' },
];

export const PER_DIEM_CATEGORIES = {
    LODGING: ['5400 Direct Travel', '5450 Direct Lodging', '8320 G&A Travel'],
    MEALS: ['5500 Direct Meals and Incidental']
};
